# -*- coding: utf-8 -*-
"""Activity Exemplar_ Course 2 Python Notebook Terjemahan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W42lkP9ZG4tBZam06plLmwgRrc35-KvJ

# **Proyek Automatidata**
**Dasar-Dasar Ilmu Data**

# **Mengidentifikasi tipe data dan variabel yang relevan menggunakan Python**

### **Membangun dataframe**
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/2017 Yellow Taxi Trip Data.csv')
print("done")

#Periksa informasi ringkasan tentang dataframe
df.head(10)

df.info()

df.describe()

# Mengurutkan data berdasarkan jarak tempuh dari nilai maksimum ke nilai minimum.

df_sort = df.sort_values(by=['trip_distance'],ascending=False)
df_sort.head(10)

# Mengurutkan data berdasarkan jumlah total dan cetak 20 nilai teratas.
total_amount_sorted = df.sort_values(
    ['total_amount'], ascending=False)['total_amount']
total_amount_sorted.head(20)

# Mengurutkan data berdasarkan jumlah total dan cetak 20 nilai terbawah.
total_amount_sorted.tail(20)

# Berapa banyak dari setiap jenis pembayaran yang terwakili dalam data?
df['payment_type'].value_counts()

# Berapakah rata-rata tip untuk perjalanan yang dibayar dengan kartu kredit?
avg_cc_tip = df[df['payment_type']==1]['tip_amount'].mean()
print('Avg. cc tip:', avg_cc_tip)

# Berapakah rata-rata tip untuk perjalanan yang dibayar tunai?
avg_cash_tip = df[df['payment_type']==2]['tip_amount'].mean()
print('Avg. cash tip:', avg_cash_tip)

# Berapa kali setiap ID vendor muncul dalam data?
df['VendorID'].value_counts()

# Berapakah rata-rata total pendapatan untuk setiap vendor?
df.groupby(['VendorID']).mean(numeric_only=True)[['total_amount']]

# Saring data hanya untuk pembayaran kartu kredit.
credit_card = df[df['payment_type']==1]

# Saring data khusus kartu kredit hanya untuk jumlah penumpang.
credit_card['passenger_count'].value_counts()

# Hitung jumlah tip rata-rata untuk setiap jumlah penumpang (hanya pembayaran kartu kredit).
credit_card.groupby(['passenger_count']).mean(numeric_only=True)[['tip_amount']]